<a href="https://colab.research.google.com/github/lucaspaludo/learning-pytorch-fundamentals/blob/main/1_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [5]:
lista = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
lista

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
np1 = np.random.rand(3, 4)
np1

array([[0.73562266, 0.39640889, 0.28817752, 0.94807907],
       [0.84058117, 0.92057481, 0.05803404, 0.68738676],
       [0.53025694, 0.51475042, 0.76833951, 0.98505237]])

In [8]:
np1.dtype

dtype('float64')

In [9]:
np1 = np.random.rand(3)
np1

array([0.31348588, 0.75275215, 0.75659188])

In [10]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-1.5516,  0.7412,  1.8874, -0.2356],
        [ 0.7230,  0.5695, -1.6376, -0.1712],
        [-2.0785, -2.5326,  0.6512,  1.4620]])

In [11]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
np2 = np.random.rand(3, 4)
np2

array([[0.0431888 , 0.78595267, 0.56061437, 0.93149402],
       [0.22768015, 0.97077233, 0.34835148, 0.27106033],
       [0.58178883, 0.36173626, 0.36387547, 0.3643786 ]])

In [13]:
tensor_from_numpy = torch.tensor(np2)
tensor_from_numpy

tensor([[0.0432, 0.7860, 0.5606, 0.9315],
        [0.2277, 0.9708, 0.3484, 0.2711],
        [0.5818, 0.3617, 0.3639, 0.3644]], dtype=torch.float64)

In [14]:
tensor_2d.dtype

torch.float32