<a href="https://colab.research.google.com/github/lucaspaludo/learning-pytorch-fundamentals/blob/main/2_opacoes_com_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

tensor = tensor.reshape(2, 5)
tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor = tensor.view(5, 2)
tensor

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
tensor2 = torch.arange(10)
tensor2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor2 = tensor2.reshape(2, -1)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor2 = tensor2.reshape(-1, 5)
tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor3 = torch.arange(10)
tensor3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor4 = tensor3.view(2, 5)
tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# diferença entre reshape e view:


In [ ]:
tensor5 = torch.arange(10)
tensor5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor6 = tensor5.reshape(2, 5)
tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
tensor5[1] = 1500
tensor5

tensor([   0, 1500,    2,    3,    4,    5,    6,    7,    8,    9])

In [ ]:
tensor6 #mudanças com reshape e view serão aplicadas automaticamente

tensor([[   0, 1500,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
# Slices
tensor7 = torch.arange(10)
tensor7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# pegando um item específico
tensor7[7]

tensor(7)

In [ ]:
# fatiando
tensor8 = tensor7.reshape(5, 2)
tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
tensor8[:, 1]

tensor([1, 3, 5, 7, 9])

In [ ]:
tensor8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])