<a href="https://colab.research.google.com/github/lucaspaludo/learning-pytorch-fundamentals/blob/main/3_operacoes_matematicas_com_tensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensorA = torch.tensor([1, 2, 3, 4])
tensorB = torch.tensor([5, 6, 7, 8])

In [3]:
tensorA + tensorB

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensorA, tensorB)

tensor([ 6,  8, 10, 12])

In [5]:
tensorB - tensorA

tensor([4, 4, 4, 4])

In [6]:
torch.sub(tensorB, tensorA)

tensor([4, 4, 4, 4])

In [7]:
tensorA * tensorB

tensor([ 5, 12, 21, 32])

In [8]:
torch.mul(tensorA, tensorB)

tensor([ 5, 12, 21, 32])

In [9]:
tensorB / tensorA

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
torch.div(tensorB, tensorA)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
tensorB % tensorA

tensor([0, 0, 1, 0])

In [12]:
torch.remainder(tensorB, tensorA)

tensor([0, 0, 1, 0])

In [13]:
tensorA ** tensorB

tensor([    1,    64,  2187, 65536])

In [14]:
torch.pow(tensorA, tensorB)

tensor([    1,    64,  2187, 65536])

In [15]:
tensorA.add(tensorB)

tensor([ 6,  8, 10, 12])

In [16]:
#tensorA = tensorA + tensorB
tensorA.add_(tensorB)


tensor([ 6,  8, 10, 12])

In [17]:
tensorA

tensor([ 6,  8, 10, 12])